import { useMemo, useState } from "react";

const CIRCLE_LIMIT = 20;
const circles = [{ id: "family", name: "Family" }, { id: "close", name: "Close friends" }, { id: "work", name: "Work" }];
const names = ["Maya Chen", "Jon Bell", "Sofia Reyes", "Andre Lewis", "Nora Patel", "Eli Brooks", "Ava Martin", "Theo Grant", "Lena Ortiz", "Caleb Ross", "Zoe Kim", "Miles Carter", "Iris Cooper", "Noah Price", "Mia Turner", "Owen Reed", "Jade Foster", "Leo Hughes", "Ruby Allen", "Finn Perry", "Tessa Cole", "Kai Morgan", "Ella Stone", "Ben Wright", "Amara King", "Dylan Ward", "Priya Shah", "Lucas Gray", "Mila Scott", "Ethan Young", "Grace Hill", "Mateo Cruz", "Ivy James", "Henry Fox", "Sadie Park", "Cole Baker"];
const colors = ["#d77658", "#5d7c78", "#756595", "#ce9b43", "#b55c7d", "#4d7bb5"];
const initialPeople = names.map((name, index) => {
  const hostFollows = index < 24;
  const memberships = hostFollows ? (index % 5 === 0 ? ["family"] : index % 5 === 1 ? ["close"] : index % 5 === 2 ? ["work"] : index % 5 === 3 ? ["family", "close"] : []) : [];
  return { id: index + 1, name, handle: `@${name.toLowerCase().replace(" ", ".")}`, circles: memberships, color: colors[index % colors.length], followsHost: index % 3 !== 1, hostFollows, followedByHost: hostFollows ? `2026-0${(index % 8) + 1}-${String((index % 27) + 1).padStart(2, "0")}` : null, followedHost: `2026-0${(index % 8) + 1}-${String((index % 27) + 1).padStart(2, "0")}`, followers: `${(index + 2) * 340}`, posts: `${48 + index * 7}` };
});
const sortOptions = [{ id: "default", label: "Default" }, { id: "latest", label: "Date followed: Latest" }, { id: "earliest", label: "Date followed: Earliest" }];
const viewTypes = ["Posts", "Stories", "Reels", "Reposts"];

export default function App() {
  const [people, setPeople] = useState(initialPeople), [tab, setTab] = useState("circles"), [query, setQuery] = useState(""), [active, setActive] = useState([]), [selected, setSelected] = useState(new Set()), [circleEditor, setCircleEditor] = useState(null), [viewing, setViewing] = useState(null), [viewDraft, setViewDraft] = useState(viewTypes), [messaging, setMessaging] = useState(null), [light, setLight] = useState(false), [sort, setSort] = useState("default"), [sortOpen, setSortOpen] = useState(false), [postViews, setPostViews] = useState({});
  const shown = useMemo(() => {
    let list = tab === "circles" ? people.filter((person) => person.hostFollows) : tab === "following" ? people.filter((person) => person.hostFollows) : people.filter((person) => person.followsHost);
    if (tab === "circles" && active.length) list = list.filter((person) => person.circles.some((circle) => active.includes(circle)));
    list = list.filter((person) => `${person.name} ${person.handle}`.toLowerCase().includes(query.toLowerCase().trim()));
    if (sort !== "default") { const dateKey = tab === "followers" ? "followedHost" : "followedByHost"; list = [...list].sort((a, b) => sort === "latest" ? (b[dateKey] || "").localeCompare(a[dateKey] || "") : (a[dateKey] || "").localeCompare(b[dateKey] || "")); }
    return list;
  }, [people, tab, active, query, sort]);
  const suggestions = people.filter((person) => !person.hostFollows && `${person.name} ${person.handle}`.toLowerCase().includes(query.toLowerCase().trim()));
  const allShownSelected = shown.length > 0 && shown.every((person) => selected.has(person.id));
  const someShownSelected = shown.some((person) => selected.has(person.id)) && !allShownSelected;
  const memberCounts = people.reduce((counts, person) => { person.circles.forEach((id) => { counts[id] = (counts[id] || 0) + 1; }); return counts; }, {});
  const selectTab = (view) => { setTab(view); setSelected(new Set()); setActive([]); };
  const toggleCircle = (id) => setActive(active.includes(id) ? active.filter((circle) => circle !== id) : [...active, id]);
  const toggleSelected = (id, checked) => { const next = new Set(selected); checked ? next.add(id) : next.delete(id); setSelected(next); };
  const toggleAllShown = (checked) => { const next = new Set(selected); shown.forEach((person) => checked ? next.add(person.id) : next.delete(person.id)); setSelected(next); };
  const setFollowing = (id, value) => setPeople((current) => current.map((person) => person.id === id ? { ...person, hostFollows: value, circles: value ? person.circles : [], followedByHost: value && !person.followedByHost ? "2026-09-24" : person.followedByHost } : person));
  const openCircleEditor = (person) => { const ids = selected.size ? [...selected] : [person.id]; const draft = Object.fromEntries(people.filter((item) => ids.includes(item.id)).map((item) => [item.id, [...item.circles]])); setCircleEditor({ ids, draft, error: null }); };
  const toggleEditorCircle = (circleId, checked) => setCircleEditor((editor) => ({ ...editor, error: null, draft: Object.fromEntries(editor.ids.map((id) => [id, checked ? [...new Set([...editor.draft[id], circleId])] : editor.draft[id].filter((id) => id !== circleId)])) }));
  const saveCircleEditor = () => {
    const proposed = people.map((person) => circleEditor.ids.includes(person.id) ? { ...person, circles: circleEditor.draft[person.id] } : person);
    const counts = proposed.reduce((result, person) => { person.circles.forEach((id) => { result[id] = (result[id] || 0) + 1; }); return result; }, {});
    const overflow = circles.find((circle) => (counts[circle.id] || 0) > CIRCLE_LIMIT);
    if (overflow) { const current = memberCounts[overflow.id] || 0; const proposedCount = counts[overflow.id]; setCircleEditor({ ...circleEditor, error: { id: overflow.id, current, proposed: proposedCount, needed: proposedCount - CIRCLE_LIMIT } }); return; }
    setPeople(proposed); setSelected(new Set()); setCircleEditor(null);
  };
  const actionFor = (person, suggested = false) => suggested ? [person.followsHost ? "Follow Back" : "Follow"] : tab === "circles" ? ["View", "Circle", "Unfollow"] : tab === "following" ? ["Following", "Message"] : [person.hostFollows ? "Following" : "Follow Back"];
  const hostAvatar = <div className="host-avatar-large" aria-label="host_user avatar">M</div>;
  const renderRow = (person, suggested = false) => <article className={`reference-row ${tab === "circles" ? "circle-row" : "relationship-row"} ${suggested ? "suggested-row" : ""}`} key={person.id}>{!suggested && <input className="check" type="checkbox" checked={selected.has(person.id)} onChange={(event) => toggleSelected(person.id, event.target.checked)} aria-label={`Select ${person.name}`} />}<div className="person-avatar" style={{ background: person.color }}>{person.name.split(" ").map((part) => part[0])}</div><div className="person-info"><strong>{person.name}</strong><span>{person.handle}</span></div>{tab === "circles" && !suggested && <div className="chips">{person.circles.map((id) => <span className="chip" key={id}>{circles.find((circle) => circle.id === id).name}</span>)}</div>}<div className="row-actions">{actionFor(person, suggested).map((action) => <button key={action} onClick={() => action === "View" ? (setViewing(person), setViewDraft(postViews[person.id] || viewTypes)) : action === "Circle" ? openCircleEditor(person) : action === "Message" ? setMessaging(person) : action === "Unfollow" || action === "Following" ? setFollowing(person.id, false) : setFollowing(person.id, true)}>{action}</button>)}</div></article>;

  if (messaging) return <main className="message-page"><header className="message-topbar"><button className="message-back" onClick={() => setMessaging(null)} aria-label="Back to account views">←</button>{hostAvatar}<div className="message-recipient"><strong>{messaging.name}<span className="verified" aria-label="Verified">✓</span></strong><span>{messaging.handle}</span></div></header><section className="message-profile"><div className="message-photo-placeholder">{hostAvatar}</div><h1>{messaging.name}<span className="verified" aria-label="Verified">✓</span></h1><p>{messaging.handle}</p><p>{messaging.followers} followers · {messaging.posts} posts</p><p>You've followed this account since {messaging.followedByHost?.slice(0, 4) || "2026"}</p></section><form className="message-composer" onSubmit={(event) => event.preventDefault()}><input placeholder="Message..." aria-label={`Message ${messaging.name}`} /><button type="submit" aria-label="Send message">➤</button></form></main>;

  return <main className={light ? "shell light" : "shell dark"}><div className="reference-shell"><header className="topbar"><div className="brand"><span className="brand-mark">◎</span>circles</div><button className="theme-toggle" onClick={() => setLight(!light)} aria-label="Toggle color theme">{light ? "☾" : "☼"}</button></header><section className="reference-header"><div className="reference-profile"><div className="reference-profile-avatar">M</div><div><h2>host_user</h2><p>Your private account view</p><p>5 Followers · 3 Following</p></div></div><button className="manage-btn" aria-label="Manage circles">＋</button></section><nav className="reference-tabs" aria-label="Account views">{["circles", "following", "followers"].map((view) => <button key={view} className={`reference-tab ${tab === view ? "active" : ""}`} onClick={() => selectTab(view)}>{view[0].toUpperCase() + view.slice(1)}</button>)}</nav><div className="reference-tools"><label className="search-wrap"><span aria-hidden="true">⌕</span><input className="reference-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search username or display name" aria-label="Search username or display name" /></label><div className="sort-wrap"><button className="reference-sort" onClick={() => setSortOpen(!sortOpen)} aria-expanded={sortOpen} aria-haspopup="dialog">⇅ Sort</button>{sortOpen && <div className="sort-panel" role="dialog" aria-label="Sort by"><h3>Sort by</h3>{sortOptions.map((option) => <label key={option.id} className="sort-option"><input type="radio" name="sort" checked={sort === option.id} onChange={() => { setSort(option.id); setSortOpen(false); }} />{option.label}</label>)}</div>}</div></div><div className="tab-slot">{tab === "circles" ? <div className="filter-row">{circles.map((circle) => <button key={circle.id} className={`filter ${active.includes(circle.id) ? "selected" : ""}`} onClick={() => toggleCircle(circle.id)}>{circle.name}</button>)}</div> : <span aria-hidden="true" />}</div><div className="selection-bar"><label><input type="checkbox" checked={allShownSelected} ref={(input) => { if (input) input.indeterminate = someShownSelected; }} onChange={(event) => toggleAllShown(event.target.checked)} aria-label="Select all visible accounts" />Select all</label><span>{selected.size} selected</span></div><div className="reference-list">{shown.map((person) => renderRow(person))}</div><section className="suggested-section"><h3>Suggested users</h3><div className="reference-list">{suggestions.map((person) => renderRow(person, true))}</div></section></div>
    {circleEditor && <dialog open className="modal" aria-modal="true"><div className="modal-form"><button className="close" onClick={() => setCircleEditor(null)} aria-label="Close circle manager">×</button><p className="eyebrow">CIRCLE MANAGER</p><h2>{circleEditor.ids.length} selected {circleEditor.ids.length === 1 ? "person" : "people"}</h2>{circleEditor.error && <p id="capacity-error" className="capacity-error" role="alert">{circles.find((circle) => circle.id === circleEditor.error.id).name} has {circleEditor.error.current} / {CIRCLE_LIMIT} members. This change would make it {circleEditor.error.proposed} / {CIRCLE_LIMIT}; remove at least {circleEditor.error.needed} member{circleEditor.error.needed === 1 ? "" : "s"} before saving.</p>}{circles.map((circle) => { const states = circleEditor.ids.map((id) => circleEditor.draft[id].includes(circle.id)); const checked = states.every(Boolean); const mixed = states.some(Boolean) && !checked; return <label className={`manage-row ${circleEditor.error?.id === circle.id ? "capacity-invalid" : ""}`} key={circle.id}><span><input type="checkbox" checked={checked} ref={(input) => { if (input) input.indeterminate = mixed; }} onChange={(event) => toggleEditorCircle(circle.id, event.target.checked)} aria-describedby={circleEditor.error?.id === circle.id ? "capacity-error" : undefined} />{circle.name}</span><small>{memberCounts[circle.id] || 0} / {CIRCLE_LIMIT} members</small></label>; })}<div className="dialog-actions"><button className="secondary" onClick={() => setCircleEditor(null)}>Cancel</button><button className="primary" onClick={saveCircleEditor}>Save Changes</button></div></div></dialog>}
    {viewing && <dialog open className="modal" aria-modal="true"><div className="modal-form"><button className="close" onClick={() => setViewing(null)} aria-label="Close post views">×</button><p className="eyebrow">YOUR PRIVATE VIEW</p><h2>Post Views</h2><p className="dialog-copy">Choose what you see from <strong>{viewing.name}</strong>. This does not change who can see your posts.</p><div className="view-options">{viewTypes.map((type) => <label key={type}><input type="checkbox" checked={viewDraft.includes(type)} onChange={(event) => setViewDraft(event.target.checked ? [...viewDraft, type] : viewDraft.filter((value) => value !== type))} />{type}</label>)}</div><div className="dialog-actions"><button className="secondary" onClick={() => setViewing(null)}>Cancel</button><button className="primary" onClick={() => { setPostViews({ ...postViews, [viewing.id]: viewDraft }); setViewing(null); }}>Save Changes</button></div></div></dialog>}
  </main>;
}
